<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class SkillSeeder extends Seeder
{
    public function run(): void
    {
        $skills = [
            // --- Technical Skills ---
            ['JavaScript', 'code'],
            ['TypeScript', 'code_blocks'],
            ['Python', 'developer_mode'],
            ['PHP', 'terminal'],
            ['C++', 'data_object'],
            ['C#', 'data_object'],
            ['Java', 'coffee'],
            ['Kotlin', 'data_object'],
            ['Swift', 'rocket_launch'],
            ['Go', 'data_object'],
            ['Rust', 'build'],
            ['Ruby', 'diamond'],
            ['HTML', 'language'],
            ['CSS', 'style'],
            ['Tailwind CSS', 'palette'],
            ['Bootstrap', 'widgets'],
            ['Laravel', 'bolt'],
            ['Symfony', 'architecture'],
            ['React', 'blur_circular'],
            ['Next.js', 'blur_on'],
            ['Vue.js', 'visibility'],
            ['Nuxt.js', 'layers'],
            ['Angular', 'donut_large'],
            ['Svelte', 'flare'],
            ['Node.js', 'dns'],
            ['Express.js', 'hub'],
            ['NestJS', 'nest_eco'],
            ['Django', 'filter_frames'],
            ['Flask', 'science'],
            ['FastAPI', 'speed'],
            ['ASP.NET', 'web'],
            ['Spring Boot', 'spa'],
            ['GraphQL', 'schema'],
            ['REST API', 'api'],
            ['SQL', 'table_chart'],
            ['PostgreSQL', 'database'],
            ['MySQL', 'storage'],
            ['SQLite', 'grid_on'],
            ['MongoDB', 'forest'],
            ['Firebase', 'local_fire_department'],
            ['Supabase', 'cloud'],
            ['Redis', 'memory'],
            ['Docker', 'anchor'],
            ['Kubernetes', 'hub'],
            ['Git', 'commit'],
            ['GitHub', 'integration_instructions'],
            ['GitLab', 'token'],
            ['Bitbucket', 'merge'],
            ['CI/CD', 'settings_suggest'],
            ['AWS', 'cloud'],
            ['Azure', 'cloud_sync'],
            ['Google Cloud', 'cloud_queue'],
            ['Linux', 'terminal'],
            ['Bash Scripting', 'console'],
            ['Networking', 'lan'],
            ['Cybersecurity', 'lock'],
            ['WebSockets', 'sync'],
            ['WebRTC', 'videocam'],
            ['Blockchain', 'token'],
            ['Solidity', 'currency_bitcoin'],
            ['Smart Contracts', 'receipt_long'],
            ['Solana', 'currency_exchange'],
            ['Ethereum', 'currency_bitcoin'],
            ['IPFS', 'hub'],
            ['AI Integration', 'smart_toy'],
            ['Machine Learning', 'psychology'],
            ['Deep Learning', 'insights'],
            ['TensorFlow', 'cognition'],
            ['PyTorch', 'bolt'],
            ['Data Visualization', 'bar_chart'],
            ['Power BI', 'monitoring'],
            ['Tableau', 'monitor_heart'],
            ['Excel Advanced', 'grid_on'],
            ['Automation', 'auto_mode'],
            ['UI/UX Design', 'brush'],
            ['Figma', 'design_services'],
            ['Adobe XD', 'brush'],
            ['Adobe Photoshop', 'photo'],
            ['Illustrator', 'format_paint'],
            ['After Effects', 'animation'],
            ['3D Modeling', 'view_in_ar'],
            ['Blender', 'view_in_ar'],
            ['Unity', 'games'],
            ['Unreal Engine', 'videogame_asset'],
            ['Game Development', 'sports_esports'],
            ['SEO', 'search'],
            ['Content Writing', 'edit'],
            ['Technical Writing', 'description'],
            ['Testing', 'bug_report'],
            ['Unit Testing', 'check_circle'],
            ['Integration Testing', 'rule'],
            ['Jest', 'science'],
            ['Mocha', 'science'],
            ['Cypress', 'science'],
            ['Postman', 'api'],
            ['Swagger', 'api'],
            ['DevOps', 'integration_instructions'],
            ['Agile Methodology', 'developer_board'],
            ['Scrum', 'dashboard'],
            ['Product Management', 'inventory_2'],
            ['System Design', 'architecture'],
            ['Data Structures', 'data_array'],
            ['Algorithms', 'functions'],

            // --- Soft Skills ---
            ['Communication', 'chat'],
            ['Teamwork', 'groups'],
            ['Problem Solving', 'psychology'],
            ['Leadership', 'military_tech'],
            ['Adaptability', 'autorenew'],
            ['Time Management', 'schedule'],
            ['Creativity', 'lightbulb'],
            ['Critical Thinking', 'psychology_alt'],
            ['Conflict Resolution', 'handshake'],
            ['Attention to Detail', 'search_check'],
            ['Emotional Intelligence', 'favorite'],
            ['Decision Making', 'fact_check'],
            ['Work Ethic', 'workspace_premium'],
            ['Collaboration', 'group_work'],
            ['Empathy', 'diversity_3'],
            ['Negotiation', 'gavel'],
            ['Presentation Skills', 'present_to_all'],
            ['Active Listening', 'hearing'],
            ['Analytical Thinking', 'insights'],
            ['Public Speaking', 'record_voice_over'],
            ['Mentoring', 'school'],
            ['Coaching', 'support_agent'],
            ['Customer Service', 'support'],
            ['Organization', 'event_note'],
            ['Networking (Professional)', 'hub'],
            ['Self-Motivation', 'self_improvement'],
            ['Resilience', 'bolt'],
            ['Multitasking', 'widgets'],
            ['Project Planning', 'task_alt'],
            ['Strategic Thinking', 'timeline'],
            ['Stress Management', 'spa'],
            ['Research Skills', 'search'],
            ['Flexibility', 'compare_arrows'],
            ['Cultural Awareness', 'language'],
            ['Accountability', 'fact_check'],
            ['Innovation', 'emoji_objects'],
            ['Goal Setting', 'flag'],
            ['Learning Agility', 'psychology'],
            ['Open-mindedness', 'sentiment_satisfied'],
            ['Ethical Judgment', 'balance']
        ];

        $data = [];
        foreach ($skills as [$title, $icon]) {
            $data[] = [
                'title' => strtolower($title),
                'logo' => '<span class="material-symbols-outlined">' . $icon . '</span>',
                'type' => $this->isSoftSkill($title) ? 'soft' : 'technical',
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        DB::table('skills')->insert($data);
    }

    private function isSoftSkill(string $title): bool
    {
        $softSkills = [
            'Communication', 'Teamwork', 'Problem Solving', 'Leadership',
            'Adaptability', 'Time Management', 'Creativity', 'Critical Thinking',
            'Conflict Resolution', 'Attention to Detail', 'Emotional Intelligence',
            'Decision Making', 'Work Ethic', 'Collaboration', 'Empathy', 'Negotiation',
            'Presentation Skills', 'Active Listening', 'Analytical Thinking',
            'Public Speaking', 'Mentoring', 'Coaching', 'Customer Service',
            'Organization', 'Networking (Professional)', 'Self-Motivation',
            'Resilience', 'Multitasking', 'Project Planning', 'Strategic Thinking',
            'Stress Management', 'Research Skills', 'Flexibility', 'Cultural Awareness',
            'Accountability', 'Innovation', 'Goal Setting', 'Learning Agility',
            'Open-mindedness', 'Ethical Judgment'
        ];

        return in_array($title, $softSkills);
    }
}
