<?php

return [

   /*
    |--------------------------------------------------------------------------
    | Restricted Subdomains
    |--------------------------------------------------------------------------
    |
    | List of subdomains that cannot be used as portfolio subdomains
    |
    */

    'restricted' => [
        // Admin / management
        'admin',
        'administrator',
        'adminpanel',
        'admin-console',
        'control',
        'controlpanel',
        'dashboard',
        'manage',
        'manager',
        'management',
        'console',
        'portal',
        'cp',
        'panel',

        // Auth / account
        'auth',
        'login',
        'signin',
        'logout',
        'signup',
        'register',
        'account',
        'accounts',
        'profile',
        'profiles',
        'settings',
        'preferences',
        'user',
        'users',
        'member',
        'members',
        'billing',
        'billingportal',

        // Email / mail infra
        'mail',
        'email',
        'webmail',
        'postmaster',
        'mailer',
        'smtp',
        'imap',
        'pop',
        'mx',
        'nofity',
        'mailer',
        'newsletter',

        // System / infra
        'www',
        'root',
        'host',
        'hostname',
        'server',
        'servers',
        'sys',
        'system',
        'status',
        'health',
        'monitor',
        'metrics',
        'logs',
        'log',
        'adminlog',
        'support',
        'help',
        'helpdesk',
        'supportcenter',
        'contact',

        // Dev / staging / testing
        'dev',
        'development',
        'staging',
        'stage',
        'test',
        'testing',
        'qa',
        'beta',
        'demo',
        'sandbox',
        'local',
        'localhost',
        'localdev',
        'ci',
        'cicd',
        'pipeline',
        'build',
        'jenkins',
        'travis',
        'circleci',
        'github-actions',
        'actions',
        'workflow',

        // Security / infra services
        'secure',
        'security',
        'ssl',
        'cert',
        'certificate',
        'vpn',
        'ssh',
        'sftp',
        'ftp',
        'dns',
        'ns',
        'ns1',
        'ns2',
        'cdn',
        'cache',
        'proxy',
        'gateway',
        'api',
        'apis',
        'webhook',
        'webhooks',
        'webhook-receiver',

        // Payment / commercial
        'payments',
        'payment',
        'billing',
        'invoice',
        'invoices',
        'checkout',
        'subscribe',
        'subscription',
        'paypal',
        'stripe',
        'pay',
        'merchant',
        'shop',
        'store',
        'orders',
        'cart',

        // Product / marketing / legal
        'blog',
        'news',
        'press',
        'media',
        'marketing',
        'ads',
        'advertise',
        'careers',
        'jobs',
        'faq',
        'about',
        'terms',
        'privacy',
        'legal',
        'tos',
        'policies',
        'policy',
        'impressum',

        // Developer tools / repos
        'git',
        'github',
        'gitlab',
        'bitbucket',
        'repo',
        'repository',
        'composer',
        'npm',
        'docker',
        'k8s',
        'kubernetes',
        'helm',
        'grafana',
        'prometheus',
        'kibana',
        'elastic',
        'logstash',
        'jenkins',

        // Common system and misc
        'www2',
        'api2',
        'api1',
        'mail1',
        'smtp1',
        'ftp1',
        'dev1',
        'test1',
        'www1',
        'admin1',
        'support1',
        'statuspage',
        'status',
        'payments',
        'billing',
        'static',
        'assets',
        'cdn',
        'img',
        'images',
        'image',
        'static-assets',

        // Generics & reserved words
        'example',
        'examples',
        'example1',
        'example2',
        'invalid',
        'none',
        'null',
        'undefined',
        'anonymous',
        'anonymoususer',
        'anonymous-user',
        'guest',
        'system',
        'operator',

        // Short / sensitive names
        'api-docs',
        'apidocs',
        'docs',
        'documentation',
        'oauth',
        'oauth2',
        'sso',
        'openid',
        'developer',
        'developers',
        'devops',
        'ops',
        'operator',
        'operators',

        // Payment processors, marketplaces (block to avoid impersonation)
        'amazon',
        'paypal',
        'stripe',
        'google',
        'facebook',
        'twitter',
        'linkedin',
        'apple',
        'microsoft',

        // SEO / abuse prevention
        'search',
        'crawler',
        'bot',
        'spider',
        'crawl',
        'scraper',
        'scanner',

        // Common support tools / integrations
        'intercom',
        'zendesk',
        'helpcenter',
        'helpdesk',
        'freshdesk',
        'drift',
        'giscus',

        // Misc
        'api-v1',
        'api-v2',
        'v1',
        'v2',
        'v3',
        'version',
        'beta-test',
        'alpha',
        'release',
    ]
];
